model:
  name: 'MinkUNet34'
  in_feat_size: 1
  out_classes: 19

dataset:
  version: 'mini'
  name: 'SynLiDAR'
  dataset_path: '/path/to/SynLiDAR'
  mapping_path: '/path/to/cosmix-intensity/utils/datasets/_resources/synlidar_semantickitti.yaml'
  target: 'SemanticKITTI'
  target_path: '/path/to/SemanticKitti/dataset'
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: true
  use_intensity: false


pipeline:
  epochs: 100
  steps: null
  gpus: [0, 1]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: '/path/to/cosmix-intensity/experiments/pretrained/synlidar/semantickitti'
  validate_target: true

  dataloader:
    batch_size: 4
    num_workers: 16

  optimizer:
    name: 'SGD'
    lr: 0.01

  scheduler:
    name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 2


  wandb:
    run_name: 'SOURCE-WARMUP-SynLiDAR2SemanticKITTI'
    project_name: 'cosmix-intensity'
    entity_name: 'cosmix-intensity'
    offline: false
