# Model must have name, out_classes and params, being params the ordered list of input parameters to given model name
model:
  name: 'MinkUNet34'
  out_classes: 19
  params:
    in_channels: 4
    out_channels: 19
  features:
    - coordinates
    - features

dataset:
  version: 'mini'
  name: 'SynLiDAR'
  dataset_path: '/path/to/SynLiDAR'
  mapping_path: '/path/to/cosmix-intensity/utils/datasets/_resources/synlidar_semantickitti.yaml'
  target: 'SemanticKITTI'
  target_path: '/path/to/SemanticKitti/dataset'
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: true
  use_intensity: false
  transforms:
    train:
      - type: "RandomRotate"
        angle: [ -1, 1 ]
        axis: "z"
        center: [ 0, 0, 0 ]
        p: 0.5
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]
      - type: "RandomScale"
        scale: [ 0.9, 1.1 ]
      - type: "RandomFlip"
        p: 0.5
      - type: "RandomJitter"
        sigma: 0.005
        clip: 0.02
      - type: "GridSample"
        grid_size: 0.05
        hash_type: "fnv"
        mode: "train"
        keys: [ "coord", "strength", "segment" ]
        return_grid_coord: true
      - type: "ToTensor"
      - type: "Collect"
        keys: [ "coord", "grid_coord", "segment" ]
        feat_keys: [ "coord", "strength" ]
    val:
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]
      - type: "GridSample"
        grid_size: 0.05
        hash_type: "fnv"
        mode: "train"
        keys: [ "coord", "strength", "segment" ]
        return_grid_coord: true
      - type: "ToTensor"
      - type: "Collect"
        keys: [ "coord", "grid_coord", "segment" ]
        feat_keys: [ "coord", "strength" ]
    test:
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]

pipeline:
  epochs: 200
  steps: null
  gpus: [0, 1]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: '/path/to/cosmix-intensity/experiments/idas/pretrained'
  validate_target: true

  dataloader:
    batch_size: 4
    num_workers: 16

  optimizer:
    name: 'SGD'
    lr: 0.01

  scheduler:
    name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 0
    log_every_n_steps: 50


  wandb:
    run_name: 'SOURCE-WARMUP-SynLiDAR2SemanticKITTI'
    project_name: 'cosmix-intensity'
    entity_name: 'cosmix-intensity'
    offline: false
